services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    restart: on-failure
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-container:3306/hotel_app?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=my-pass
    container_name: hotel-app
    networks:
      - backend


  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: my-pass
      MYSQL_DATABASE: hotel_app
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    container_name: mysql-container
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend
networks:
  backend:

volumes:
  mysql-data:

