version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-spring-boot-app:latest
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASS=root
    depends_on:
      - mysql
    networks:
      - app-network
    command: ["./wait-for-it.sh", "mysql:3306", "--", "java", "-jar", "/app.jar"]

  mysql:
    image: mysql:latest
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hotel_app
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      retries: 20
      interval: 5s
      timeout: 2s

networks:
  app-network:
    driver: bridge
