spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    driverClassName: org.postgresql.Driver
    url: "jdbc:postgresql://test_hotel_app_frnv_user:PCq7P1DLa0JueekRjFHQ5hP8ZuZIj88m@dpg-cqd2i4eehbks73bo6hp0-a.oregon-postgres.render.com:5432/test_hotel_app_frnv"
    username: test_hotel_app_frnv_user
    password: PCq7P1DLa0JueekRjFHQ5hP8ZuZIj88m
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 6MB
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
mail:
  hotel: "top@hotel.bg"
  host: localhost
  port: 1025
  username: ${MAIL_USER:hotel}
  password: ${MAIL_PASS:hotel}

server:
  servlet:
    session:
      timeout: 30m



  #Cloudinary Properties
#cloudinary:
  #api-key: 
  #api-secret: 
  #cloud-name:

