spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${AZURE_MYSQL_CONNECTIONSTRING}
    username: ${DB_USER:root}
    password: ${DB_PASS:1234}
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 6MB
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  servlet:
    session:
      timeout: 30m
