spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
    open-in-view: false


  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 6MB
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  sql:
    init:
      mode: never

mail:
  hotel: "top@hotel.bg"
  host: localhost
  port: 1025
  username: ${MAIL_USER:hotel}
  password: ${MAIL_PASS:hotel}

server:
  servlet:
    session:
      timeout: 30m



  #Cloudinary Properties
#cloudinary:
  #api-key: 
  #api-secret: 
  #cloud-name:

