spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://dpg-cqd2i4eehbks73bo6hp0-a.oregon-postgres.render.com/test_hotel_app_frnv
    username: ${SPRING_DATASOURCE_USERNAME:test_hotel_app_frnv_user}
    password: ${SPRING_DATASOURCE_PASSWORD:PCq7P1DLa0JueekRjFHQ5hP8ZuZIj88m}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    defer-datasource-initialization: true

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 6MB
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  sql:
    init:
      mode: never

mail:
  hotel: "top@hotel.bg"
  host: localhost
  port: 1025
  username: ${MAIL_USER:hotel}
  password: ${MAIL_PASS:hotel}

server:
  servlet:
    session:
      timeout: 30m



  #Cloudinary Properties
#cloudinary:
  #api-key: 
  #api-secret: 
  #cloud-name:

