spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${z}
    username: ${DB_USER:root}
    password: ${DB_PASS:1234}
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 6MB
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
mail:
  hotel: "top@hotel.bg"
  host: localhost
  port: 1025
  username: ${MAIL_USER:hotel}
  password: ${MAIL_PASS:hotel}

server:
  servlet:
    session:
      timeout: 30m